name: CI for Robot application
on:
  pull_request:
    branches: [main, development]
  push:
    branches: [main, development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: CI for Robot application
        working-directory: ./app
        run: |
          npm i
          npm run build
          npm run test
          npm run test:cov
